### ISSUE TITLE
Godoc page Not Found

### ISSUE THREAD

**Issue by vaibhavk** [taskcluster/websocktunnel#37]
Godoc link in the description of repository leads to nowhere, while searching in godoc specifically [whclient's doc](https://godoc.org/github.com/taskcluster/webhooktunnel/whclient) doesn't exists while [util's doc](https://godoc.org/github.com/taskcluster/webhooktunnel/util) exsists.

**Comment by djmitche** [comment]
@vaibhavk I think you were looking at how to fix this?

**Comment by vaibhavk** [comment]
@djmitche description can have the link https://godoc.org/github.com/taskcluster/websocktunnel/client

**Comment by djmitche** [comment]
OK -- want to make a short PR for that?

**Comment by djmitche** [comment]
I think this is done now.. https://godoc.org/github.com/taskcluster/websocktunnel looks pretty good!
